### ISSUE TITLE
Safe Area may not be drawn correctly after playing

### ISSUE THREAD

**Issue by su10** [su10/AutoScreen-for-Device-Simulator#1]
When using Device Simulator 3.x.x or higher, the Safe Area is not drawn correctly once the device is changed after playing Unity.

# Reproduction
  1. Enter play mode.
  2. Change device in Device Simulator.
  3. Exit play mode.
  4. Change device in Device Simulator.
  5. The Safe Area is not drawn correctly.

# Workaround
After the drawing has gone wrong, you can do any of the following to get it to draw correctly

* Change the device on the Device Simulator
* Click in the Console window.
* Click on any GameObject in the Hierarchy window

**Comment by a-suto** [comment]
fixed: e13813461618c109934c5c6f45837b63c7147b05

**Comment by su10** [comment]
fixed: e13813461618c109934c5c6f45837b63c7147b05
